<?php
function get__currency__items(){
	$currency__ids = array(
	    "AGLD" =>'AGLD',
	    "FJD" =>'FJD',
	    "MXN" =>'MXN',
	    "LVL" =>'LVL',
	    "SCR" =>'SCR',
	    "CDF" =>'CDF',
	    "BBD" =>'BBD',
	    "HNL" =>'HNL',
	    "UGX" =>'UGX',
	    "GLM" =>'GLM',
	    "NEAR" =>'NEAR',
	    "AIOZ" =>'AIOZ',
	    "AUDIO" =>'AUDIO',
	    "FARM" =>'FARM',
	    "SDG" =>'SDG',
	    "IQD" =>'IQD',
	    "GMD" =>'GMD',
	    "RBN" =>'RBN',
	    "ZRX" =>'ZRX',
	    "BCH" =>'BCH',
	    "MYR" =>'MYR',
	    "FKP" =>'FKP',
	    "XOF" =>'XOF',
	    "GMT" =>'GMT',
	    "SEK" =>'SEK',
	    "GNF" =>'GNF',
	    "MZN" =>'MZN',
	    "QAR" =>'QAR',
	    "IRR" =>'IRR',
	    "GNO" =>'GNO',
	    "GNT" =>'GNT',
	    "FLR" =>'FLR',
	    "XPD" =>'XPD',
	    "THB" =>'THB',
	    "XPF" =>'XPF',
	    "ABT" =>'ABT',
	    "BDT" =>'BDT',
	    "T" =>'T',
	    "LYD" =>'LYD',
	    "KWD" =>'KWD',
	    "DIA" =>'DIA',
	    "XPT" =>'XPT',
	    "ISK" =>'ISK',
	    "JUP" =>'JUP',
	    "ACH" =>'ACH',
	    "MINA" =>'MINA',
	    "PAB" =>'PAB',
	    "ACS" =>'ACS',
	    "SGD" =>'SGD',
	    "BLUR" =>'BLUR',
	    "REN" =>'REN',
	    "ELA" =>'ELA',
	    "REP" =>'REP',
	    "ADA" =>'ADA',
	    "REQ" =>'REQ',
	    "STORJ" =>'STORJ',
	    "CHF" =>'CHF',
	    "HRK" =>'HRK',
	    "RARI" =>'RARI',
	    "DJF" =>'DJF',
	    "RARE" =>'RARE',
	    "PAX" =>'PAX',
	    "VND" =>'VND',
	    "CHZ" =>'CHZ',
	    "KYD" =>'KYD',
	    "XRP" =>'XRP',
	    "JASMY" =>'JASMY',
	    "SHP" =>'SHP',
	    "INDEX" =>'INDEX',
	    "TJS" =>'TJS',
	    "AED" =>'AED',
	    "FIDA" =>'FIDA',
	    "SAND" =>'SAND',
	    "DKK" =>'DKK',
	    "WCFG" =>'WCFG',
	    "ZWD" =>'ZWD',
	    "OCEAN" =>'OCEAN',
	    "BGN" =>'BGN',
	    "UMA" =>'UMA',
	    "FOX" =>'FOX',
	    "ZWL" =>'ZWL',
	    "HTG" =>'HTG',
	    "RGT" =>'RGT',
	    "BHD" =>'BHD',
	    "ENJ" =>'ENJ',
	    "COVAL" =>'COVAL',
	    "CGLD" =>'CGLD',
	    "KZT" =>'KZT',
	    "YFII" =>'YFII',
	    "DIMO" =>'DIMO',
	    "GRT" =>'GRT',
	    "AFN" =>'AFN',
	    "ENS" =>'ENS',
	    "UNI" =>'UNI',
	    "FX" =>'FX',
	    "HUF" =>'HUF',
	    "BIF" =>'BIF',
	    "XTZ" =>'XTZ',
	    "AURORA" =>'AURORA',
	    "EOS" =>'EOS',
	    "GST" =>'GST',
	    "FORT" =>'FORT',
	    "SWFTC" =>'SWFTC',
	    "BIT" =>'BIT',
	    "NAD" =>'NAD',
	    "SKK" =>'SKK',
	    "SKL" =>'SKL',
	    "TMM" =>'TMM',
	    "GTC" =>'GTC',
	    "PEN" =>'PEN',
	    "WST" =>'WST',
	    "SHPING" =>'SHPING',
	    "TMT" =>'TMT',
	    "CLF" =>'CLF',
	    "EUROC" =>'EUROC',
	    "GTQ" =>'GTQ',
	    "CLP" =>'CLP',
	    "DNT" =>'DNT',
	    "TND" =>'TND',
	    "CLV" =>'CLV',
	    "SLE" =>'SLE',
	    "FLOW" =>'FLOW',
	    "UPI" =>'UPI',
	    "SLL" =>'SLL',
	    "DOP" =>'DOP',
	    "DOT" =>'DOT',
	    "1INCH" =>'1INCH',
	    "MAD" =>'MAD',
	    "TOP" =>'TOP',
	    "PGK" =>'PGK',
	    "GYEN" =>'GYEN',
	    "UNFI" =>'UNFI',
	    "CNH" =>'CNH',
	    "NCT" =>'NCT',
	    "WLUNA" =>'WLUNA',
	    "POWR" =>'POWR',
	    "ERN" =>'ERN',
	    "VOXEL" =>'VOXEL',
	    "RLC" =>'RLC',
	    "CNY" =>'CNY',
	    "ATOM" =>'ATOM',
	    "QUICK" =>'QUICK',
	    "BLZ" =>'BLZ',
	    "BOBA" =>'BOBA',
	    "TONE" =>'TONE',
	    "BMD" =>'BMD',
	    "SNT" =>'SNT',
	    "PHP" =>'PHP',
	    "SNX" =>'SNX',
	    "RLY" =>'RLY',
	    "COP" =>'COP',
	    "USD" =>'USD',
	    "API3" =>'API3',
	    "HOPR" =>'HOPR',
	    "ROSE" =>'ROSE',
	    "XYO" =>'XYO',
	    "SOL" =>'SOL',
	    "ETB" =>'ETB',
	    "ETC" =>'ETC',
	    "SOS" =>'SOS',
	    "VUV" =>'VUV',
	    "LAK" =>'LAK',
	    "OGN" =>'OGN',
	    "UST" =>'UST',
	    "CELR" =>'CELR',
	    "ETH" =>'ETH',
	    "BND" =>'BND',
	    "AUCTION" =>'AUCTION',
	    "BADGER" =>'BADGER',
	    "ALL" =>'ALL',
	    "HIGH" =>'HIGH',
	    "TRB" =>'TRB',
	    "BNT" =>'BNT',
	    "GYD" =>'GYD',
	    "BOB" =>'BOB',
	    "MDL" =>'MDL',
	    "TRU" =>'TRU',
	    "AMD" =>'AMD',
	    "DREP" =>'DREP',
	    "TRY" =>'TRY',
	    "LBP" =>'LBP',
	    "MDT" =>'MDT',
	    "AERGO" =>'AERGO',
	    "EUR" =>'EUR',
	    "AMP" =>'AMP',
	    "ORCA" =>'ORCA',
	    "RON" =>'RON',
	    "NGN" =>'NGN',
	    "CRC" =>'CRC',
	    "PKR" =>'PKR',
	    "ANG" =>'ANG',
	    "EGLD" =>'EGLD',
	    "SPELL" =>'SPELL',
	    "PUNDIX" =>'PUNDIX',
	    "LCX" =>'LCX',
	    "CRO" =>'CRO',
	    "PLA" =>'PLA',
	    "SRD" =>'SRD',
	    "TTD" =>'TTD',
	    "CRV" =>'CRV',
	    "MNDE" =>'MNDE',
	    "NU" =>'NU',
	    "ANT" =>'ANT',
	    "RPL" =>'RPL',
	    "AOA" =>'AOA',
	    "PLN" =>'PLN',
	    "LDO" =>'LDO',
	    "QNT" =>'QNT',
	    "MAGIC" =>'MAGIC',
	    "ALICE" =>'ALICE',
	    "PLU" =>'PLU',
	    "MUSD" =>'MUSD',
	    "MUSE" =>'MUSE',
	    "OP" =>'OP',
	    "MGA" =>'MGA',
	    "NIO" =>'NIO',
	    "APE" =>'APE',
	    "ETH2" =>'ETH2',
	    "BUSD" =>'BUSD',
	    "ARPA" =>'ARPA',
	    "BRL" =>'BRL',
	    "MCO2" =>'MCO2',
	    "ALCX" =>'ALCX',
	    "00" =>'00',
	    "MATIC" =>'MATIC',
	    "STD" =>'STD',
	    "APT" =>'APT',
	    "CTX" =>'CTX',
	    "STG" =>'STG',
	    "PNG" =>'PNG',
	    "TVK" =>'TVK',
	    "IOTX" =>'IOTX',
	    "SHIB" =>'SHIB',
	    "ZAR" =>'ZAR',
	    "STN" =>'STN',
	    "CUC" =>'CUC',
	    "BSD" =>'BSD',
	    "STX" =>'STX',
	    "QI" =>'QI',
	    "CUP" =>'CUP',
	    "TWD" =>'TWD',
	    "RSD" =>'RSD',
	    "BSV" =>'BSV',
	    "MSOL" =>'MSOL',
	    "OMG" =>'OMG',
	    "BAND" =>'BAND',
	    "BTC" =>'BTC',
	    "NKN" =>'NKN',
	    "UYU" =>'UYU',
	    "ARB" =>'ARB',
	    "CVC" =>'CVC',
	    "CVE" =>'CVE',
	    "OMR" =>'OMR',
	    "MIR" =>'MIR',
	    "KES" =>'KES',
	    "LOKA" =>'LOKA',
	    "BTN" =>'BTN',
	    "SVC" =>'SVC',
	    "ARS" =>'ARS',
	    "CVX" =>'CVX',
	    "ANKR" =>'ANKR',
	    "SUSHI" =>'SUSHI',
	    "ALGO" =>'ALGO',
	    "SYLO" =>'SYLO',
	    "UZS" =>'UZS',
	    "WBTC" =>'WBTC',
	    "DYP" =>'DYP',
	    "ASM" =>'ASM',
	    "RUB" =>'RUB',
	    "AST" =>'AST',
	    "MANA" =>'MANA',
	    "MKD" =>'MKD',
	    "ATA" =>'ATA',
	    "DZD" =>'DZD',
	    "QSP" =>'QSP',
	    "NMR" =>'NMR',
	    "JEP" =>'JEP',
	    "MKR" =>'MKR',
	    "KGS" =>'KGS',
	    "LIT" =>'LIT',
	    "ICP" =>'ICP',
	    "ZEC" =>'ZEC',
	    "XAF" =>'XAF',
	    "NEST" =>'NEST',
	    "XAG" =>'XAG',
	    "ZEN" =>'ZEN',
	    "DESO" =>'DESO',
	    "LOOM" =>'LOOM',
	    "DOGE" =>'DOGE',
	    "HBAR" =>'HBAR',
	    "PRO" =>'PRO',
	    "TZS" =>'TZS',
	    "XAU" =>'XAU',
	    "MLN" =>'MLN',
	    "PRQ" =>'PRQ',
	    "AUD" =>'AUD',
	    "KHR" =>'KHR',
	    "IDR" =>'IDR',
	    "CTSI" =>'CTSI',
	    "BWP" =>'BWP',
	    "RWF" =>'RWF',
	    "KAVA" =>'KAVA',
	    "C98" =>'C98',
	    "SYN" =>'SYN',
	    "MMK" =>'MMK',
	    "NOK" =>'NOK',
	    "SYP" =>'SYP',
	    "CRPT" =>'CRPT',
	    "LKR" =>'LKR',
	    "GAL" =>'GAL',
	    "CZK" =>'CZK',
	    "XCD" =>'XCD',
	    "AVT" =>'AVT',
	    "XCN" =>'XCN',
	    "SZL" =>'SZL',
	    "YER" =>'YER',
	    "LSETH" =>'LSETH',
	    "ORN" =>'ORN',
	    "MASK" =>'MASK',
	    "AWG" =>'AWG',
	    "NPR" =>'NPR',
	    "AAVE" =>'AAVE',
	    "MNT" =>'MNT',
	    "PRIME" =>'PRIME',
	    "GBP" =>'GBP',
	    "BYN" =>'BYN',
	    "PERP" =>'PERP',
	    "BYR" =>'BYR',
	    "BOND" =>'BOND',
	    "YFI" =>'YFI',
	    "LQTY" =>'LQTY',
	    "TIME" =>'TIME',
	    "BICO" =>'BICO',
	    "BZD" =>'BZD',
	    "MOP" =>'MOP',
	    "MONA" =>'MONA',
	    "AXL" =>'AXL',
	    "AXS" =>'AXS',
	    "TRAC" =>'TRAC',
	    "MPL" =>'MPL',
	    "COMP" =>'COMP',
	    "WAXL" =>'WAXL',
	    "HFT" =>'HFT',
	    "WAMPL" =>'WAMPL',
	    "OOKI" =>'OOKI',
	    "DEXT" =>'DEXT',
	    "FORTH" =>'FORTH',
	    "GHST" =>'GHST',
	    "KMF" =>'KMF',
	    "MATH" =>'MATH',
	    "IDEX" =>'IDEX',
	    "GEL" =>'GEL',
	    "AVAX" =>'AVAX',
	    "AZN" =>'AZN',
	    "UAH" =>'UAH',
	    "KNC" =>'KNC',
	    "ALEPH" =>'ALEPH',
	    "GFI" =>'GFI',
	    "MRO" =>'MRO',
	    "LPT" =>'LPT',
	    "MRU" =>'MRU',
	    "GODS" =>'GODS',
	    "PYG" =>'PYG',
	    "JMD" =>'JMD',
	    "PYR" =>'PYR',
	    "BTRST" =>'BTRST',
	    "SUKU" =>'SUKU',
	    "DAI" =>'DAI',
	    "GGP" =>'GGP',
	    "DAR" =>'DAR',
	    "FET" =>'FET',
	    "CBETH" =>'CBETH',
	    "VEF" =>'VEF',
	    "ZMK" =>'ZMK',
	    "LRC" =>'LRC',
	    "REPV2" =>'REPV2',
	    "LRD" =>'LRD',
	    "MTL" =>'MTL',
	    "VES" =>'VES',
	    "ZMW" =>'ZMW',
	    "USDT" =>'USDT',
	    "OXT" =>'OXT',
	    "DASH" =>'DASH',
	    "ILS" =>'ILS',
	    "ILV" =>'ILV',
	    "GHS" =>'GHS',
	    "KPW" =>'KPW',
	    "MEDIA" =>'MEDIA',
	    "JOD" =>'JOD',
	    "GUSD" =>'GUSD',
	    "HKD" =>'HKD',
	    "LSL" =>'LSL',
	    "KEEP" =>'KEEP',
	    "CAD" =>'CAD',
	    "EEK" =>'EEK',
	    "MUR" =>'MUR',
	    "IMP" =>'IMP',
	    "GIP" =>'GIP',
	    "IMX" =>'IMX',
	    "LTC" =>'LTC',
	    "USDC" =>'USDC',
	    "METIS" =>'METIS',
	    "XMON" =>'XMON',
	    "INJ" =>'INJ',
	    "KRL" =>'KRL',
	    "LTL" =>'LTL',
	    "SAR" =>'SAR',
	    "VGX" =>'VGX',
	    "MVR" =>'MVR',
	    "TRIBE" =>'TRIBE',
	    "INR" =>'INR',
	    "INV" =>'INV',
	    "POND" =>'POND',
	    "KRW" =>'KRW',
	    "JPY" =>'JPY',
	    "SBD" =>'SBD',
	    "XLM" =>'XLM',
	    "DDX" =>'DDX',
	    "LINK" =>'LINK',
	    "MWK" =>'MWK',
	    "SUPER" =>'SUPER',
	    "POLS" =>'POLS',
	    "KSM" =>'KSM',
	    "FIL" =>'FIL',
	    "POLY" =>'POLY',
	    "RNDR" =>'RNDR',
	    "BAL" =>'BAL',
	    "BAM" =>'BAM',
	    "GALA" =>'GALA',
	    "EGP" =>'EGP',
	    "FIS" =>'FIS',
	    "RAD" =>'RAD',
	    "BAT" =>'BAT',
	    "MXC" =>'MXC',
	    "NZD" =>'NZD',
	    "RAI" =>'RAI',
	    "COTI" =>'COTI',
	); 
 
 	return $currency__ids;
}

function scrape__current_price_api(){
	$transienst_id = 'cur_scrape__api';
	$data = get_transient($transienst_id);
	if( empty( $data ) || isset( $_GET['force'] ) ) {
		# المفتاح من خيار لوحة التحكم — لا مفاتيح داخل الكود (v1.2.0)
		$api_key = get_option( 'yc_currencyfreaks_key' );
		if ( empty( $api_key ) ) {
			return array();
		}
		$response = wp_remote_get( 'https://api.currencyfreaks.com/latest?apikey='.rawurlencode( $api_key ), array( 'timeout' => 15 ) );
		if ( is_wp_error( $response ) ) {
			return array();
		}
		$data = json_decode( wp_remote_retrieve_body( $response ), true );
		set_transient($transienst_id,$data,3600);
	}	
	return $data;
}

function get_current_price_value($currency__item=''){

	$currency__item = ( ( isset( $_COOKIE['currency_mode_v1'] ) && $currency__item == '' ) ) ? $_COOKIE['currency_mode_v1'] : $currency__item;
	if( $currency__item == '' ) $currency__item = get_option('currency');
	if( $currency__item == '' ) $currency__item = 'USD';
	
	$scrape__current_price_api = scrape__current_price_api();

	return number_format((float) $scrape__current_price_api['rates'][$currency__item], 2, '.', '');
	
}

function get_site_currency( $currency__item='',$currency__shows=array()){
	$currency__item = ( ( isset( $_COOKIE['currency_mode_v1'] ) && $currency__item == '' ) ) ? $_COOKIE['currency_mode_v1'] : $currency__item;
	if( $currency__item == '' ) $currency__item = get_option('currency');
	if( $currency__item == '' ) $currency__item = 'USD';

	if( empty( $currency__shows ) ) $currency__shows = get_option('currency__shows');

	$currency__shows = ( (  is_array( $currency__shows ) ) ) ? $currency__shows : array();
	foreach ( $currency__shows as $k => $v ) {
		if( $v['item__id'] == $currency__item ){
			return $v;
		}
	}
}

function price($price_value,$currency__item=''){

	$currency__item = ( ( isset( $_COOKIE['currency_mode_v1'] ) && $currency__item == '' ) ) ? $_COOKIE['currency_mode_v1'] : $currency__item;
	if( $currency__item == '' ) $currency__item = get_option('currency');
	if( $currency__item == '' ) $currency__item = 'USD';

	$get_current_price_value = get_current_price_value($currency__item);
	return (INT) $price_value*$get_current_price_value;
}